// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Ej_ButtonL2St

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Bt01 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Bt01, 100);
    lv_obj_set_height(ui_Bt01, 50);
    lv_obj_set_align(ui_Bt01, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Bt01, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Bt01, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextArea1 = lv_textarea_create(ui_Bt01);
    lv_obj_set_width(ui_TextArea1, lv_pct(90));
    lv_obj_set_height(ui_TextArea1, lv_pct(90));
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea1, 25);
    lv_textarea_set_text(ui_TextArea1, "Bt01");
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");



}
