// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Ej_ButtonL2St

#include "ui.h"

void Presionar_Bt11(lv_event_t * e)
{
	// Your code here
}

void Presionar_Bt12(lv_event_t * e)
{
	// Your code here
}

void Presionar_Bt21(lv_event_t * e)
{
	// Your code here
}

void Presionar_Bt22(lv_event_t * e)
{
	// Your code here
}

void Presionar_BtOk(lv_event_t * e)
{
	// Your code here
}
