// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: Ej_ButtonL2St

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Presionar_Bt11(lv_event_t * e);
void Presionar_Bt12(lv_event_t * e);
void Presionar_Bt21(lv_event_t * e);
void Presionar_Bt22(lv_event_t * e);
void Presionar_BtOk(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
