// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: Ej_ButtonL2St

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container4 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, lv_pct(100));
    lv_obj_set_height(ui_Container4, lv_pct(100));
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabViewWiFi = lv_tabview_create(ui_Container4);
    lv_tabview_set_tab_bar_size(ui_TabViewWiFi, 25);
    lv_obj_set_width(ui_TabViewWiFi, lv_pct(100));
    lv_obj_set_height(ui_TabViewWiFi, lv_pct(100));
    lv_obj_set_align(ui_TabViewWiFi, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TabViewWiFi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    ui_TabPageWiFiCautivo = lv_tabview_add_tab(ui_TabViewWiFi, "WiFi Cautivo");
    lv_obj_set_style_radius(ui_TabPageWiFiCautivo, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TabPageWiFiCautivo, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabPageWiFiCautivo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_TabPageWiFiCautivo);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, lv_pct(100));
    lv_obj_set_height(ui_Container1, lv_pct(90));
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, lv_pct(10));
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container11 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container11);
    lv_obj_set_width(ui_Container11, lv_pct(98));
    lv_obj_set_height(ui_Container11, lv_pct(23));
    lv_obj_set_x(ui_Container11, 0);
    lv_obj_set_y(ui_Container11, lv_pct(-38));
    lv_obj_set_align(ui_Container11, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container11, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container11, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabSSID = lv_label_create(ui_Container11);
    lv_obj_set_width(ui_LabSSID, lv_pct(60));
    lv_obj_set_height(ui_LabSSID, lv_pct(35));
    lv_obj_set_x(ui_LabSSID, lv_pct(16));
    lv_obj_set_y(ui_LabSSID, lv_pct(0));
    lv_obj_set_align(ui_LabSSID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabSSID, "xx.xx.xx.xx");

    ui_Label3 = lv_label_create(ui_Container11);
    lv_obj_set_width(ui_Label3, lv_pct(29));
    lv_obj_set_height(ui_Label3, lv_pct(35));
    lv_obj_set_x(ui_Label3, lv_pct(-33));
    lv_obj_set_y(ui_Label3, lv_pct(0));
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Red WiFi (SSID).:");

    ui_Container12 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container12);
    lv_obj_set_width(ui_Container12, lv_pct(98));
    lv_obj_set_height(ui_Container12, lv_pct(23));
    lv_obj_set_x(ui_Container12, 0);
    lv_obj_set_y(ui_Container12, -31);
    lv_obj_set_align(ui_Container12, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container12, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container12, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabIP = lv_label_create(ui_Container12);
    lv_obj_set_width(ui_LabIP, lv_pct(60));
    lv_obj_set_height(ui_LabIP, lv_pct(35));
    lv_obj_set_x(ui_LabIP, lv_pct(16));
    lv_obj_set_y(ui_LabIP, lv_pct(0));
    lv_obj_set_align(ui_LabIP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabIP, "xx.xx.xx.xx");

    ui_Label4 = lv_label_create(ui_Container12);
    lv_obj_set_width(ui_Label4, lv_pct(29));
    lv_obj_set_height(ui_Label4, lv_pct(35));
    lv_obj_set_x(ui_Label4, lv_pct(-33));
    lv_obj_set_y(ui_Label4, lv_pct(0));
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Direccion IP.:");

    ui_Container13 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container13);
    lv_obj_set_width(ui_Container13, lv_pct(98));
    lv_obj_set_height(ui_Container13, lv_pct(23));
    lv_obj_set_x(ui_Container13, 0);
    lv_obj_set_y(ui_Container13, 26);
    lv_obj_set_align(ui_Container13, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container13, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container13, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabDNS = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_LabDNS, lv_pct(60));
    lv_obj_set_height(ui_LabDNS, lv_pct(35));
    lv_obj_set_x(ui_LabDNS, lv_pct(16));
    lv_obj_set_y(ui_LabDNS, lv_pct(0));
    lv_obj_set_align(ui_LabDNS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabDNS, "xx.xx.xx.xx");

    ui_Label7 = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_Label7, lv_pct(29));
    lv_obj_set_height(ui_Label7, lv_pct(35));
    lv_obj_set_x(ui_Label7, lv_pct(-33));
    lv_obj_set_y(ui_Label7, lv_pct(0));
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Direccion DNS.:");

    ui_Container14 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container14);
    lv_obj_set_width(ui_Container14, lv_pct(98));
    lv_obj_set_height(ui_Container14, lv_pct(23));
    lv_obj_set_x(ui_Container14, 0);
    lv_obj_set_y(ui_Container14, 85);
    lv_obj_set_align(ui_Container14, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container14, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container14, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabMAC = lv_label_create(ui_Container14);
    lv_obj_set_width(ui_LabMAC, lv_pct(60));
    lv_obj_set_height(ui_LabMAC, lv_pct(35));
    lv_obj_set_x(ui_LabMAC, lv_pct(16));
    lv_obj_set_y(ui_LabMAC, lv_pct(0));
    lv_obj_set_align(ui_LabMAC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabMAC, "xx:xx:xx:xx:xx:xx");

    ui_Label9 = lv_label_create(ui_Container14);
    lv_obj_set_width(ui_Label9, lv_pct(29));
    lv_obj_set_height(ui_Label9, lv_pct(35));
    lv_obj_set_x(ui_Label9, lv_pct(-33));
    lv_obj_set_y(ui_Label9, lv_pct(0));
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Direccion MAC.:");

    ui_Container2 = lv_obj_create(ui_TabPageWiFiCautivo);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, lv_pct(100));
    lv_obj_set_height(ui_Container2, lv_pct(17));
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, lv_pct(-45));
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bt1 = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_Bt1, lv_pct(35));
    lv_obj_set_height(ui_Bt1, lv_pct(85));
    lv_obj_set_x(ui_Bt1, lv_pct(-25));
    lv_obj_set_y(ui_Bt1, lv_pct(0));
    lv_obj_set_align(ui_Bt1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Bt1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Bt1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Bt1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Conectar WiFi");

    ui_Bt2 = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_Bt2, lv_pct(35));
    lv_obj_set_height(ui_Bt2, lv_pct(85));
    lv_obj_set_x(ui_Bt2, lv_pct(25));
    lv_obj_set_y(ui_Bt2, lv_pct(0));
    lv_obj_set_align(ui_Bt2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Bt2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Bt2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Bt2);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Desconectar WiFi");

    ui_BtConectado = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_BtConectado, 30);
    lv_obj_set_height(ui_BtConectado, 30);
    lv_obj_set_align(ui_BtConectado, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtConectado, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BtConectado, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtConectado, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtConectado, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtConectado, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPageConectarWiFi = lv_tabview_add_tab(ui_TabViewWiFi, "Conectar WiFi");
    lv_obj_set_style_radius(ui_TabPageConectarWiFi, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TabPageConectarWiFi, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabPageConectarWiFi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_TabPageConectarWiFi);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, lv_pct(100));
    lv_obj_set_height(ui_Container3, lv_pct(17));
    lv_obj_set_x(ui_Container3, 0);
    lv_obj_set_y(ui_Container3, lv_pct(-45));
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container3, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bt3 = lv_button_create(ui_Container3);
    lv_obj_set_width(ui_Bt3, lv_pct(35));
    lv_obj_set_height(ui_Bt3, lv_pct(85));
    lv_obj_set_x(ui_Bt3, lv_pct(-25));
    lv_obj_set_y(ui_Bt3, lv_pct(0));
    lv_obj_set_align(ui_Bt3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Bt3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Bt3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Bt3);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Conectar WiFi");

    ui_Bt4 = lv_button_create(ui_Container3);
    lv_obj_set_width(ui_Bt4, lv_pct(35));
    lv_obj_set_height(ui_Bt4, lv_pct(85));
    lv_obj_set_x(ui_Bt4, lv_pct(25));
    lv_obj_set_y(ui_Bt4, lv_pct(0));
    lv_obj_set_align(ui_Bt4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Bt4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Bt4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Bt4);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "ReScan WiFi");

    ui_BtConectado1 = lv_button_create(ui_Container3);
    lv_obj_set_width(ui_BtConectado1, 30);
    lv_obj_set_height(ui_BtConectado1, 30);
    lv_obj_set_align(ui_BtConectado1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtConectado1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BtConectado1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtConectado1, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtConectado1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtConectado1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelConectarWiFi = lv_obj_create(ui_Container4);
    lv_obj_set_width(ui_PanelConectarWiFi, lv_pct(75));
    lv_obj_set_height(ui_PanelConectarWiFi, lv_pct(53));
    lv_obj_set_x(ui_PanelConectarWiFi, 0);
    lv_obj_set_y(ui_PanelConectarWiFi, 39);
    lv_obj_set_align(ui_PanelConectarWiFi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelConectarWiFi, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_PanelConectarWiFi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelConectarWiFi, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelConectarWiFi, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelConectarWiFi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelConectarWiFi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelConectarWiFi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelConectarWiFi, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_PanelConectarWiFi, 10, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelConectarWiFi, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelConectarWiFi, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_LabelConectarWiFi = lv_label_create(ui_PanelConectarWiFi);
    lv_obj_set_width(ui_LabelConectarWiFi, lv_pct(100));
    lv_obj_set_height(ui_LabelConectarWiFi, lv_pct(45));
    lv_obj_set_x(ui_LabelConectarWiFi, 0);
    lv_obj_set_y(ui_LabelConectarWiFi, -15);
    lv_obj_set_align(ui_LabelConectarWiFi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelConectarWiFi, "");
    lv_obj_set_style_text_color(ui_LabelConectarWiFi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelConectarWiFi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelConectarWiFi, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelConectarWiFi, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LabelConectarWiFi, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtOk = lv_button_create(ui_PanelConectarWiFi);
    lv_obj_set_width(ui_BtOk, lv_pct(48));
    lv_obj_set_height(ui_BtOk, lv_pct(25));
    lv_obj_set_x(ui_BtOk, lv_pct(0));
    lv_obj_set_y(ui_BtOk, lv_pct(40));
    lv_obj_set_align(ui_BtOk, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtOk, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BtOk, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_BtOk);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Aceptar");

    lv_obj_add_event_cb(ui_Bt1, ui_event_Bt1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Bt2, ui_event_Bt2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Bt3, ui_event_Bt3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Bt4, ui_event_Bt4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtOk, ui_event_BtOk, LV_EVENT_ALL, NULL);

}
