// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Ej_ButtonL2St

#include "ui.h"
#include <WiFi.h>
#include <WiFiManager.h>
#include <ConectarWiFi_IoT.h>




void Presionar_Bt01(lv_event_t * e) {
	lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * btn = lv_event_get_target(e);
    if(code == LV_EVENT_CLICKED) {
		lv_label_set_text(ui_LabSSID, "SSID Conectado");
		lv_label_set_text(ui_LabIP, "IP Conectado");
		lv_label_set_text(ui_LabDNS, "DNS Conectado");
		lv_label_set_text(ui_LabMAC, "MAC Conectado");		
		lv_obj_set_style_bg_color(ui_BtConectado, lv_color_hex(0x008000), LV_PART_MAIN | LV_STATE_DEFAULT);
	}	
}

void Presionar_Bt02(lv_event_t * e) {
	lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * btn = lv_event_get_target(e);
    if(code == LV_EVENT_CLICKED) {
		lv_label_set_text(ui_LabSSID, "xx.xx.xx.xx");
		lv_label_set_text(ui_LabIP, "xx.xx.xx.xx");
		lv_label_set_text(ui_LabDNS, "xx.xx.xx.xx");
		lv_label_set_text(ui_LabMAC, "xx:xx:xx:xx:xx:xx");
		lv_obj_set_style_bg_color(ui_BtConectado, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
	}
}
