// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Ej_ButtonL2St

#ifndef _EJ_BUTTONL2ST_UI_H
#define _EJ_BUTTONL2ST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_LabSSID;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Container12;
extern lv_obj_t * ui_LabIP;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_LabDNS;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Container14;
extern lv_obj_t * ui_LabMAC;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Container2;
void ui_event_Bt1(lv_event_t * e);
extern lv_obj_t * ui_Bt1;
extern lv_obj_t * ui_Label1;
void ui_event_Bt2(lv_event_t * e);
extern lv_obj_t * ui_Bt2;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_BtConectado;
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_Container3;
void ui_event_Bt3(lv_event_t * e);
extern lv_obj_t * ui_Bt3;
extern lv_obj_t * ui_Label2;
void ui_event_Bt4(lv_event_t * e);
extern lv_obj_t * ui_Bt4;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_BtConectado1;
extern lv_obj_t * ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
