// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Ej_ButtonL2St

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Presionar_Bt01(lv_event_t * e);
void Presionar_Bt02(lv_event_t * e);
void Presionar_Bt03(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
