// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Ej_ButtonL2St

#include "ui.h"

void Presionar_Bt01(lv_event_t * e)
{
	// Your code here
}

void Presionar_Bt02(lv_event_t * e)
{
	// Your code here
}

void Presionar_Bt03(lv_event_t * e)
{
	// Your code here
}
